plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

packageExtensions:
  "@storybook/builder-vite@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      typescript: "*"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.2.0.cjs
