name: CI
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node v12.14.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
      - name: Installing
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn typecheck
